### ISSUE TITLE
Request for SootAndro-2.8.jar source code

### ISSUE THREAD

**Issue by skhanzad** [H2SO4T/RONIN#2]
Hello,

I am writing to request the source code for SootAndro-2.8.jar as we are having trouble running the jar file and need to investigate what is wrong with the code. We have encountered some issues and error messages while running the jar file and we believe that having access to the source code will help us better understand the problem and find a solution.

Would it be possible for the authors to release the SootAndro-2.8.jar source code, or provide any guidance on how we can resolve the issues we are facing? We are looking to use the tool for our research and your assistance would be greatly appreciated.

Thank you for your time and consideration.

**Comment by H2SO4T** [comment]
Dear @sourenaKhanzadeh,
I apologize for the delay and appreciate your interest in RONIN. Unfortunately, I do not have the original repository to share with you. However, I have decompiled my JAR file using an online JAR decompiler, and the decompiled code is quite similar to the original code. You can find it here: https://we.tl/t-XoMKdNJqe2

The two main files that may be of use to you are `IDOS_XAS_FI.java`, which identifies vulnerabilities, and `appTransformer.java`, which injects code into the .apk file.
